tasks:
  dev:
    command: 'tsup --watch'
    options:
      runInCI: false
      persistent: true

  build:
    command: 'tsup --dts'

  publish:
    command: 'pnpm publish --access public'
    deps:
      - build
